# your domain
domain: liuxing.test.utools.club
port: 80

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - ./config/source.yaml
  # use web file
#  - https://raw.githubusercontent.com/liuxingyx/zu1kProxypool/master/config/source.yaml
  - https://raw.githubusercontent.com/money-fly/proxypool/master/config/source.yaml
#  - https://raw.githubusercontent.com/Alex950808/proxypool038/master/config/source.yaml
#  - https://raw.githubusercontent.com/wishcaiji/proxypool/master/config/source.yaml
#  - https://raw.githubusercontent.com/grxp/proxypool/master/config/source.yaml
